# HTRflow demo pipeline
# This pipeline works well on pages with running text

steps:

# Region segmentation
- step: Segmentation
  settings:
    model: yolo
    model_settings:
       model: Riksarkivet/yolov9-regions-1
    generation_settings:
       batch_size: 2
# Line segementation
- step: Segmentation
  settings:
    model: yolo
    model_settings:
       model: Riksarkivet/yolov9-lines-within-regions-1
    generation_settings:
        batch_size: 2
# Text recognition
- step: TextRecognition
  settings:
    model: WordLevelTrocr
    model_settings:
      model: Riksarkivet/trocr-large-handwritten-hist-swe-3-char
      model_kwargs:
        # WordLevelTrOCR needs decoder attentions to locate word boundaries.
        attn_implementation: eager
    generation_settings:
      batch_size: 4
      num_beams: 1
      interpolate_pos_encoding: true
      max_new_tokens: 160
# Order regions by reading order
- step: ReadingOrderMarginalia
  settings:
    two_page: always
# Export to Alto and Page XML
- step: Export
  settings:
    dest: /home/dgxuser/erik/projects/QualityPrediction/data/eval_swedish_lion_26/htrflow_json/region_line_sl26
    format: json

